"""empty message

Revision ID: 1b91bcbc44fb
Revises: 87ac1666db75
Create Date: 2024-07-30 08:49:32.899348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b91bcbc44fb'
down_revision = '87ac1666db75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automation_tool_in_development', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('automation_tool_in_development')

    # ### end Alembic commands ###
