"""empty message

Revision ID: 572ff573de57
Revises: 4938121fb22f
Create Date: 2024-05-28 15:29:20.860350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572ff573de57'
down_revision = '4938121fb22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorship_mentee',
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mentee_id', 'mentor_id')
    )
    op.create_table('mentorship_mentor',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mentor_id', 'mentee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentorship_mentor')
    op.drop_table('mentorship_mentee')
    # ### end Alembic commands ###
