"""empty message

Revision ID: bcfa14b485ab
Revises: ab4a9bb07cda
Create Date: 2024-05-24 21:17:43.435810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfa14b485ab'
down_revision = 'ab4a9bb07cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
