"""empty message

Revision ID: d5e160ed722e
Revises: f61c81cff7ca
Create Date: 2024-07-23 09:01:08.461156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e160ed722e'
down_revision = 'f61c81cff7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False, server_default='collaboration'))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_public')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
