"""empty message

Revision ID: eca1163de3ff
Revises: cd6824a54a49
Create Date: 2024-06-14 20:59:41.794781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca1163de3ff'
down_revision = 'cd6824a54a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flowchart_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('timeline', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('timeline')
        batch_op.drop_column('flowchart_path')
        batch_op.drop_column('requirements')
        batch_op.drop_column('overview')

    # ### end Alembic commands ###
