"""empty message

Revision ID: f61c81cff7ca
Revises: 539b00886068
Create Date: 2024-07-12 13:26:19.707054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61c81cff7ca'
down_revision = '539b00886068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_chat_room')
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.create_table('_alembic_tmp_chat_room',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='fk_chat_room_creator'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
