"""empty message

Revision ID: f997e242d07a
Revises: eca1163de3ff
Create Date: 2024-06-15 23:09:50.619961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f997e242d07a'
down_revision = 'eca1163de3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flowchart', sa.Text(), nullable=True))
        batch_op.drop_column('flowchart_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flowchart_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('flowchart')

    # ### end Alembic commands ###
